# Generated by Django 6.1.1 on 2026-09-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='contacto',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comercio',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comercio',
            name='direccion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='comercio',
            name='vidriera',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='ubicacion',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
